from __future__ import annotations

from typing import Protocol

from openrelay.core import DirectoryShortcut, SessionRecord, SessionSummary

from .models import RelaySessionBinding


class RelaySessionRepository(Protocol):
    def get(self, session_id: str) -> SessionRecord: ...
    def find(self, session_id: str) -> SessionRecord | None: ...
    def find_active(self, base_key: str) -> SessionRecord | None: ...
    def has_scope(self, base_key: str) -> bool: ...
    def owner_scope(self, base_key: str) -> str: ...
    def bind_scope(self, base_key: str, session_id: str) -> None: ...
    def load_for_scope(self, base_key: str, template: SessionRecord | None = None) -> SessionRecord: ...
    def create_next(self, base_key: str, current: SessionRecord | None = None, label: str = "", **overrides: str) -> SessionRecord: ...
    def save(self, session: SessionRecord) -> SessionRecord: ...
    def save_scope(self, base_key: str, session: SessionRecord) -> SessionRecord: ...
    def list_by_scope(self, base_key: str, limit: int = 20) -> list[SessionSummary]: ...
    def resume(self, base_key: str, target: str) -> SessionRecord | None: ...
    def clear_scope(self, base_key: str) -> None: ...


class SessionBindingRepository(Protocol):
    def get(self, relay_session_id: str) -> RelaySessionBinding | None: ...
    def save(self, binding: RelaySessionBinding) -> RelaySessionBinding: ...
    def update_native_session_id(self, relay_session_id: str, native_session_id: str) -> None: ...
    def find_by_feishu_scope(self, chat_id: str, thread_id: str) -> RelaySessionBinding | None: ...
    def list_recent(self, backend: str | None = None, limit: int = 20) -> list[RelaySessionBinding]: ...


class MessageRepository(Protocol):
    def append(self, session_id: str, role: str, content: str) -> None: ...
    def list(self, session_id: str) -> list[dict[str, str]]: ...
    def clear(self, session_id: str) -> None: ...
    def count(self, session_id: str) -> int: ...
    def first(self, session_id: str, role: str) -> str: ...
    def last(self, session_id: str, role: str) -> str: ...


class SessionAliasRepository(Protocol):
    def find(self, alias_key: str) -> str | None: ...
    def save(self, alias_key: str, base_key: str) -> None: ...


class DirectoryShortcutRepository(Protocol):
    def list(self) -> tuple[DirectoryShortcut, ...]: ...
    def get(self, name: str) -> DirectoryShortcut | None: ...
    def save(self, shortcut: DirectoryShortcut) -> DirectoryShortcut: ...
    def remove(self, name: str) -> bool: ...


class MessageDedupRepository(Protocol):
    def remember(self, message_id: str) -> bool: ...
